.DEF MAX_VAL = R17
.DEF MIN_VAL = R18
.DEF COUNTER = R19

.ORG 0x00
RJMP RESET
.ORG 0x02
RJMP ISR_INT0
.ORG 0x04
RJMP ISR_INT1

RESET:

	//ENTRADAS Y SALIDAS
	LDI R16, 0x00
	OUT DDRD, R16 //PUERTO D COMO ENTRADA
	LDI R16, 0x0C
	OUT PORTD, R16 //ACTIVAMOS RESISTENCIAS DE PULL UP EN D2 Y D3

	LDI R16, 0x0F
	OUT DDRB, R16

	//INICIALIZAR STACK
	LDI R16, LOW(RAMEND)
	OUT SPL, R16
	LDI R16, HIGH(RAMEND)
	OUT SPH, R16

	//INTERRUPCIONES EXTERNAS
	LDI R16, 0x0F //AMBAS INTERRUPCIONES FLANCO DE SUBIDA
	STS EICRA, R16 
	LDI R16, 0x03 //HABILITAMOS AMBAS INTERRUPCIONES
	OUT EIMSK, R16
	

	//VARIABLES AUXILIARES
	LDI MIN_VAL, 0
	LDI MAX_VAL, 9
	LDI COUNTER, 0

	SEI //ACTIVAMOS LA BANDERA DE INTERRUPCIONES DEL SREG
MAIN:
RJMP MAIN


ISR_INT0:
	IN R16, SREG
	CPSE COUNTER, MAX_VAL
	INC COUNTER
	OUT PORTB, COUNTER
	OUT SREG, R16
	RETI

ISR_INT1:
	IN R16, SREG
	CPSE COUNTER, MIN_VAL
	DEC COUNTER
	OUT PORTB, COUNTER
	OUT SREG, R16
	RETI